### ISSUE TITLE
Build fails on MinGW-w64: SetThreadDescription/GetThreadDescription undeclared after #5246

### ISSUE THREAD

**Issue by NF0T** [aethersdr/AetherSDR#5374]
## What happened?

Building AetherSDR from a clean tree with a MinGW-w64 toolchain (reproduced with Qt's bundled `mingw1310_64`, GCC 13.1) fails to compile after the System Info dialog work landed in #5246:

```
src/core/AsyncLogWriter.cpp: In function 'void AetherSDR::{anonymous}::nameThisThread()':
src/core/AsyncLogWriter.cpp:350:5: error: 'SetThreadDescription' was not declared in this scope; did you mean 'SetThreadInformation'?
    350 |     SetThreadDescription(GetCurrentThread(), L"AsyncLogWriter");
```

The same error recurs for `SetThreadDescription` in `src/core/ThreadName.cpp` and `GetThreadDescription` in `src/core/SystemInfo.cpp` once the first failure is worked past.

## Root cause

`kernel32.dll` exports both `SetThreadDescription` and `GetThreadDescription` (Windows 10 1607+), but this mingw-w64 header snapshot's `<processthreadsapi.h>` doesn't declare either prototype. Confirmed with an isolated repro — the missing declaration is unconditional; widening `_WIN32_WINNT`/`WINVER` to `0x0A00` before including `<windows.h>` does not surface it. MSVC's Windows SDK already declares both (checked against the SDK header actually shipped on this machine), which is why this only breaks on MinGW.

Introduced by bc345850 (#5246, "System Info dialog — Threads and Logs tabs"), which added the first calls to either API anywhere in this codebase.

## Precedent

This isn't the first MinGW header gap here — #622 hit the same shape of problem for `TCP_INFO_v0`/`SIO_TCP_INFO` and was fixed the same way (declare what the header is missing, guarded to the MinGW toolchain).

## Steps to reproduce

1. Configure with a MinGW-w64 Ninja toolchain, e.g.:
   ```
   cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=<mingw Qt kit>
   ```
2. Build: `cmake --build build`
3. Compilation of `src/core/AsyncLogWriter.cpp` fails with the error above.

## Environment

- Toolchain: Qt 6.11.2's bundled `mingw1310_64` (GCC 13.1.0), Windows 11
- Likely affects any MinGW-w64 toolchain whose header snapshot predates the `SetThreadDescription`/`GetThreadDescription` declarations

## Fix

Ready — PR incoming. Declares both functions manually (`extern "C" __declspec(dllimport)`, matching the real SDK prototype exactly), guarded to `__MINGW32__` so MSVC and non-Windows builds are untouched.

---
👨🏼‍💻 Co-authored by Claude Sonnet 5
