### PR TITLE
fix(test): follow the setKeying seam in the persist diagnostics stub. Principle XI.

### PR DESCRIPTION
**Pull request by ten9876**
`main` has been red since #5516 merged. All three of `CI` (the required check), `Full Suite` and `System Libraries Canary` fail at the **Build** step:

```
tests/automation_persist_diagnostics_test.cpp:47:10: error:
  'void StubBackend::setKeying(bool)' marked 'override', but does not override
  error: invalid new-expression of abstract class type 'StubBackend'
```

## Why it reached main green

#5659 gave `IRadioBackend::setKeying` a `TxCoordinator::Operation` and an optional `Completion`. #5516's branch predates that and its new `StubBackend` implemented the older two-argument seam, so the class stayed abstract.

**This is a timing race, not a coverage gap.** The required `build` job configures with no test-disabling flag and runs `cmake --build build -j$(nproc)` with no target filter, on a `pull_request` trigger — so it compiles this target against the merge result and would have caught the conflict. It simply never saw the two changes together:

| Time (UTC) | Event |
|---|---|
| 03:29:31 | #5516's final CI run starts on `476909c18` — green, against a main without #5659 |
| 03:38:04 | #5659 merges, changing the `setKeying` seam |
| 03:52:13 | #5516 auto-merges on the 03:29 green |
| 04:19 | `CI` on main fails at Build |

Nine minutes. `main` has `strict: false`, so nothing required a re-run in the gap, and auto-merge fired on a green computed against the wrong base.

That trade-off is deliberate and documented in `ci.yml`'s own header — "We dropped the *Require branches up to date before merging* branch-protection bit because it forced a CI rerun on every PR whenever main moved… The trade-off is: CI now runs on the merged commit itself, so any semantic conflict that slipped past three-way merge surfaces on main within ~10 min." That is exactly what happened, and this PR is the intended response to it.

## Ordering

This is a **build** failure, so ninja stops before any test runs. `Full Suite` cannot reach the assertion #5763 repairs until this compiles — that PR is necessary but not sufficient on its own. Same root cause in #5659, different files, different failure modes.

## Verification

Built and run against `a449dee4a`: the target compiles clean and all 13 checks in `automation_persist_diagnostics_test` pass. `grep -rn 'void setKeying(bool)' tests/ src/` returns nothing further, so this was the only stale override left in the tree.

The stub stays inert — it has no wire behind it, and nothing in that file keys (Principle VI).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by ten9876** [comment]
Superseded and closing unmerged: #5675 landed at 04:46 and carried the same fix as a side effect of its own work, so `main` already has the corrected override at `tests/automation_persist_diagnostics_test.cpp:47` and `git grep 'void setKeying(bool)'` on `main` now returns nothing. The two diffs are functionally identical — theirs writes `TxCoordinator::` unqualified and gives `Completion` a default argument, mine spelled out `AetherSDR::` — so there is nothing left for this PR to change.

Keeping it as the written record of the root cause rather than deleting it: the break was a nine-minute race, not a coverage gap. #5516's final CI started 03:29:40Z; #5659 changed the `setKeying` seam at 03:38:04Z; #5516 auto-merged at 03:52:13Z on that stale green. The required `build` job does compile this target with no filter, so it would have caught the conflict had it run after #5659 — it simply never saw the two together, which is the trade-off `ci.yml`'s header documents for `strict: false`.

The durable fix is in the skills, not here: a green-freshness gate before /pr-land arms auto-merge. That is #5765.
