### PR TITLE
fix(gui): guard UlanziDial member type with HAVE_HIDAPI on Windows (#3343)

### LINKED ISSUE #3343: fix(gui): UlanziDialWindowsManager incomplete type breaks MinGW build without hidapi
## Bug

Introduced by #3239 (Ulanzi Dial Windows backend). MinGW builds on Windows **without** hidapi fail to compile `MainWindow.cpp` with:

```
error: cannot convert 'AetherSDR::UlanziDialBackend*' to 'AetherSDR::UlanziDialWindowsManager*' in assignment
error: invalid use of incomplete type 'class AetherSDR::UlanziDialWindowsManager'
error: no matching function for call to 'QObject::connect(AetherSDR::UlanziDialWindowsManager*&, ...)'
```

## Root cause

`MainWindow.h` declares `m_dialBackend` as `UlanziDialWindowsManager*` under `#elif defined(Q_OS_WIN)` — no `HAVE_HIDAPI` check. But `UlanziDialBackend.h` only aliases `UlanziDialWindowsManager` under `Q_OS_WIN && HAVE_HIDAPI`; without hidapi it falls through to a no-op stub class also named `UlanziDialBackend`. The member type is an incomplete forward-declared class unrelated to the alias, so all three operations (assignment, `moveToThread`, `connect`) fail.

CI uses MSVC + hidapi so this was never caught by the build gate.

## Fix

Add `&& defined(HAVE_HIDAPI)` to both the forward-declaration and member-declaration guards for `UlanziDialWindowsManager` in `MainWindow.h`. Add an `#else` fallback in both spots that forward-declares / holds `UlanziDialBackend*` (the no-op stub), keeping the no-hidapi Windows path compilable.

**PR:** NF0T/AetherSDR (pending)

## Environment

- Windows 11, MinGW GCC 13.1.0, Qt 6.11.0
- `hidapi` **not** installed (USB HID encoder support disabled)

### PR DESCRIPTION
**Pull request by NF0T**
## Problem

Introduced by #3239 (Ulanzi Dial Windows backend). MinGW builds on Windows
**without** hidapi fail on `MainWindow.cpp` with:

    error: cannot convert 'AetherSDR::UlanziDialBackend*' to
           'AetherSDR::UlanziDialWindowsManager*' in assignment
    error: invalid use of incomplete type
           'class AetherSDR::UlanziDialWindowsManager'

`MainWindow.h` declared `m_dialBackend` as `UlanziDialWindowsManager*` under
`#elif defined(Q_OS_WIN)` — no `HAVE_HIDAPI` check. But `UlanziDialBackend.h`
only aliases `UlanziDialWindowsManager` under `Q_OS_WIN && HAVE_HIDAPI`; without
hidapi it falls through to a no-op stub class. The member type is an incomplete
forward-declared class unrelated to the alias, making assignment, `moveToThread`,
and all `connect()` calls fail to compile.

CI uses MSVC + hidapi so this was never caught by the build gate.

## Fix

Add `&& defined(HAVE_HIDAPI)` to both the forward-declaration and member-
declaration guards for `UlanziDialWindowsManager` in `MainWindow.h`. Add an
`#else` fallback in both spots using `UlanziDialBackend*` (the no-op stub).

## Testing

Built on Windows 11 / MinGW GCC 13.1.0 / Qt 6.11.0 without hidapi — full
build succeeds, `AetherSDR.exe` launches. No logic change on any platform
that already compiles (Linux evdev, Windows+hidapi, macOS).

## Files changed

- `src/gui/MainWindow.h` — 6 lines (2 guard conditions + 2 `#else` entries)

## CODEOWNERS note

`src/gui/MainWindow.h` is in the **maintainer-only** tier — requires
`@ten9876` review.

Fixes #3343

### CODE REVIEW

**Review by jensenpat — APPROVED** [review]
Reviewed — no P1 issues.

**Root cause confirmed:** `MainWindow.h` declared `m_dialBackend` as `UlanziDialWindowsManager*` under bare `Q_OS_WIN`, but `UlanziDialBackend.h` only aliases that type under `Q_OS_WIN && HAVE_HIDAPI`; otherwise `UlanziDialBackend` is a no-op stub class. Member type vs. `new UlanziDialBackend` mismatch breaks MinGW-without-hidapi builds.

**Fix is correct and minimal:** the added `&& defined(HAVE_HIDAPI)` guards plus the `#else` fallback to `UlanziDialBackend*` make all four paths (Linux / Win+hidapi / Mac / else) keep the member type identical to the per-platform alias in `UlanziDialBackend.h`. Forward decls and member sit inside `namespace AetherSDR`, matching the namespaced stub. No logic change; build-only fix. CI (build, check-windows, check-macos, CodeQL) all green.

Note: `src/gui/MainWindow.h` is maintainer-only — requires @ten9876 review to satisfy branch protection before merge.
