### PR TITLE
fix(core): declare SetThreadDescription/GetThreadDescription for MinGW

### LINKED ISSUE #5374: Build fails on MinGW-w64: SetThreadDescription/GetThreadDescription undeclared after #5246
## What happened?

Building AetherSDR from a clean tree with a MinGW-w64 toolchain (reproduced with Qt's bundled `mingw1310_64`, GCC 13.1) fails to compile after the System Info dialog work landed in #5246:

```
src/core/AsyncLogWriter.cpp: In function 'void AetherSDR::{anonymous}::nameThisThread()':
src/core/AsyncLogWriter.cpp:350:5: error: 'SetThreadDescription' was not declared in this scope; did you mean 'SetThreadInformation'?
    350 |     SetThreadDescription(GetCurrentThread(), L"AsyncLogWriter");
```

The same error recurs for `SetThreadDescription` in `src/core/ThreadName.cpp` and `GetThreadDescription` in `src/core/SystemInfo.cpp` once the first failure is worked past.

## Root cause

`kernel32.dll` exports both `SetThreadDescription` and `GetThreadDescription` (Windows 10 1607+), but this mingw-w64 header snapshot's `<processthreadsapi.h>` doesn't declare either prototype. Confirmed with an isolated repro — the missing declaration is unconditional; widening `_WIN32_WINNT`/`WINVER` to `0x0A00` before including `<windows.h>` does not surface it. MSVC's Windows SDK already declares both (checked against the SDK header actually shipped on this machine), which is why this only breaks on MinGW.

Introduced by bc345850 (#5246, "System Info dialog — Threads and Logs tabs"), which added the first calls to either API anywhere in this codebase.

## Precedent

This isn't the first MinGW header gap here — #622 hit the same shape of problem for `TCP_INFO_v0`/`SIO_TCP_INFO` and was fixed the same way (declare what the header is missing, guarded to the MinGW toolchain).

## Steps to reproduce

1. Configure with a MinGW-w64 Ninja toolchain, e.g.:
   ```
   cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=<mingw Qt kit>
   ```
2. Build: `cmake --build build`
3. Compilation of `src/core/AsyncLogWriter.cpp` fails with the error above.

## Environment

- Toolchain: Qt 6.11.2's bundled `mingw1310_64` (GCC 13.1.0), Windows 11
- Likely affects any MinGW-w64 toolchain whose header snapshot predates the `SetThreadDescription`/`GetThreadDescription` declarations

## Fix

Ready — PR incoming. Declares both functions manually (`extern "C" __declspec(dllimport)`, matching the real SDK prototype exactly), guarded to `__MINGW32__` so MSVC and non-Windows builds are untouched.

---
👨🏼‍💻 Co-authored by Claude Sonnet 5

### PR DESCRIPTION
**Pull request by NF0T**
## Summary

Fixes #5374. A MinGW-w64 build fails to compile after #5246 (System Info dialog) because this mingw-w64 header snapshot doesn't declare `SetThreadDescription`/`GetThreadDescription` in `<processthreadsapi.h>`, even though `kernel32.dll` exports both (Windows 10 1607+) and MSVC's SDK already has them — see the issue for the repro, the exact compile error, and why widening `_WIN32_WINNT` doesn't help.

- Declares both functions manually (`extern "C" __declspec(dllimport)`), matching the real Windows SDK prototype exactly (verified against the SDK header shipped on this machine, not just from memory)
- Guarded to `#if defined(__MINGW32__)` — zero effect on MSVC, macOS, or Linux builds
- Applied at all three call sites: `src/core/AsyncLogWriter.cpp`, `src/core/ThreadName.cpp`, `src/core/SystemInfo.cpp`
- Duplicated across the three files rather than centralized in a shared header — matches the existing precedent already in `AsyncLogWriter.cpp` (its own comment explains why it duplicates `ThreadName.cpp`'s platform block instead of including it: this file compiles into 51 test targets vs. 6, so sharing a header with a linkable source isn't free — this is the same idiom, just for a pure prototype)
- Same shape as the project's own prior MinGW fix in #622 (`TCP_INFO_v0`/`SIO_TCP_INFO`)

No RFC needed — plain build fix, explicitly exempted per `GOVERNANCE.md`.

## Test plan

- [x] Full MinGW build (Qt 6.11.2, `mingw1310_64`) compiles clean and links `AetherSDR.exe` — confirmed by rebuilding from a failing state to a clean 1367-target build with no `FAILED`/`error:` lines
- [ ] MSVC build unaffected — not yet re-verified on this branch (the guard makes it a no-op for `cl.exe`, but flagging as unconfirmed rather than assumed)

---
👨🏼‍💻 Co-authored by Claude Sonnet 5

### CODE REVIEW

**Review by ten9876 — COMMENTED** [review]
## Issue fit

#5374: MinGW-w64's header snapshot doesn't declare `SetThreadDescription`/`GetThreadDescription` even though kernel32 exports them, so #5246's System Info work fails to compile there. The fix declares both manually behind `#if defined(__MINGW32__)`. Verified: the prototypes match the real SDK exactly (`SetThreadDescription(HANDLE, PCWSTR)`, `GetThreadDescription(HANDLE, PWSTR*)`), the guard is a strict no-op on MSVC/macOS/Linux, and all three call sites (`AsyncLogWriter`, `ThreadName`, `SystemInfo`) are covered. Same shape as the project's own #622 (`TCP_INFO_v0`) MinGW precedent. Clear-root-cause build fix, RFC-exempt.

## Scope

Three files, on-issue. `CHANGELOG.md` untouched. Preflight: no sockets.

## Blockers

None.

## Nits (non-blocking)

- The duplication rationale cites the `AsyncLogWriter` precedent, but that precedent is about not sharing a header that pulls in a **linkable source** (the 51-vs-6 test-target concern). A *pure prototype* header has no source to link, so the concern doesn't transfer — a one-line `ThreadDescriptionShims.h` would carry this identically without the three-way copy. Minor; the copy is harmless.
- Forward-compat note: if a future mingw-w64 snapshot adds these declarations, the guard produces a redeclaration — benign, since it's an identical `extern "C" __declspec(dllimport)` prototype, but worth a `#if !defined(...)`-style comment so a maintainer knows the copy can be dropped once the toolchain catches up.

## What was verified vs read

- **Verified:** prototype signatures against the SDK shape; guard is `__MINGW32__`-only; all three call sites present.
- **Not re-run:** the MSVC no-op claim (the body honestly marks it unconfirmed) — the guard makes it a preprocessor no-op, so low risk, but CI's `check-windows` is MSVC and is green.

**Recommendation: approve with nits** — mechanical, correct, precedent-backed.

File: src/core/AsyncLogWriter.cpp [hunk 1]
```diff
@@ -22,6 +22,13 @@
 #define NOMINMAX
 #endif
 #include <windows.h>
+#if defined(__MINGW32__)
```
Comment (jensenpat) [inline src/core/AsyncLogWriter.cpp:25]: Non-blocking: this same `#if defined(__MINGW32__)` is duplicated in `ThreadName.cpp` and `SystemInfo.cpp`, and it will also fire on mingw-w64 snapshots that already declare these (`WINBASEAPI HRESULT WINAPI SetThreadDescription(HANDLE, PCWSTR)` in current `processthreadsapi.h`, attributes equivalent to this `dllimport`). That should be a silent redeclaration, not a build break. If a newer kit ever complains, the VLC shape is `__MINGW64_VERSION_MAJOR < N` — but N is 10 in VLC and 12 in Bitcoin's write-up of the same gap, and the reporter has not published their `_mingw_mac.h`, so I would not pin it here.

**Review by jensenpat — COMMENTED** [review]
## Issue fit

**Yes.** #5374 is a MinGW compile break after #5246: `SetThreadDescription` undeclared at `AsyncLogWriter.cpp` / `ThreadName.cpp`, `GetThreadDescription` undeclared at `SystemInfo.cpp`, because this mingw-w64 `<processthreadsapi.h>` snapshot omits both prototypes (widening `_WIN32_WINNT` does not help). The diff adds `__MINGW32__`-guarded `extern "C" __declspec(dllimport)` declarations after `<windows.h>` at all three call sites. Prototypes match the Windows SDK (`HRESULT WINAPI SetThreadDescription(HANDLE, PCWSTR)` / `GetThreadDescription(HANDLE, PWSTR*)`) and current mingw-w64 master (`WINBASEAPI HRESULT WINAPI …`). The PR body now records a clean 1367-target MinGW link of `AetherSDR.exe` on the reporting `mingw1310_64` kit, which is the load-bearing claim earlier reviews could not confirm from CI.

## Scope

| File | What it changes | Claimed by title/body? | Verdict |
|---|---|---|---|
| `src/core/AsyncLogWriter.cpp` | MinGW `SetThreadDescription` prototype | Yes | In scope |
| `src/core/ThreadName.cpp` | MinGW `SetThreadDescription` prototype | Yes | In scope |
| `src/core/SystemInfo.cpp` | MinGW `GetThreadDescription` prototype | Yes | In scope |

Purely additive. No guard or symptom-naming comment removed, no settings/UI/public surface, no `CHANGELOG.md` (correct). Body checklist is honest: MinGW compile+link checked; MSVC marked unconfirmed. Nothing to unbundle.

## Blockers

None.

## Nits (non-blocking)

1. **Unconditional `__MINGW32__` will redeclare on kits that already have the prototypes.** mingw-w64 ≥12 ships both in `processthreadsapi.h` as `WINBASEAPI HRESULT WINAPI …`; in user mode `WINBASEAPI` is `DECLSPEC_IMPORT`, so this should be an identical C++ redeclaration rather than the dllimport-mismatch the issue triage feared. VLC still version-gated (`__MINGW64_VERSION_MAJOR < 10`) after a redefine; Bitcoin treats the header gap as pre-12.0.0. I would not hold this PR for a pin the reporter has not published. See inline on `AsyncLogWriter.cpp`.
2. **Three copies of a pure prototype.** The AsyncLogWriter 51-vs-6 rationale is about not linking `ThreadName.cpp`; a header-only shim would not undo that. Fine to leave until a fourth site appears.
3. **No CI MinGW lane.** Green `check-windows` is MSVC (`win64_msvc2022_64`). Not asking for a job on this fix.

## What was verified vs read

Read the three hunks; grepped `ThreadDescription` on PR head (3 call sites, 3 guards, plus two comment-only mentions). Compared prototypes to mingw-w64 master `processthreadsapi.h` and MSDN. Did not locally compile: the new lines are `__MINGW32__`-only and this host is macOS; CI `build` / `check-macos` / `check-windows` / `Static checks` are already green on `e7ddfb0`.

**Recommendation:** approve with nits. Next step is the operator's approval; neither nit needs code in this PR.

**Review by jensenpat — APPROVED** [review]
Approving to merge. Same verdict as the prior review on e7ddfb0: approve with nits; the nits do not need code in this PR.
