### ISSUE TITLE
automation_tx_watchdog_test: two assertions still red on main from #5659

### ISSUE THREAD

**Issue by ten9876** [aethersdr/AetherSDR#5771]
Split from #5768, which was closed by #5763 although only one of its three documented assertions was fixed.

#5763 fixed the `tx_audio_source_wiring_test` third. The two `automation_tx_watchdog_test` assertions are still red on `main`:

```
[FAIL] expired original operation receives watchdog cleanup
[FAIL] watchdog cleanup rechecks identity after synchronous replacement
```

## Confirmed on main, by CI, either side of #5763

`Full Suite` on Linux, 494 tests:

| commit | result |
|---|---|
| [`e9785f16e`](https://github.com/aethersdr/AetherSDR/commit/e9785f16e) — before #5763 | 2 failed: `tx_audio_source_wiring_test`, `automation_tx_watchdog_test` ([run 35186686201](https://github.com/aethersdr/AetherSDR/actions/runs/35186686201)) |
| [`abf90ac7a`](https://github.com/aethersdr/AetherSDR/commit/abf90ac7a) — #5763 squash | 1 failed: `automation_tx_watchdog_test` ([run 35186835229](https://github.com/aethersdr/AetherSDR/actions/runs/35186835229)) |
| [`34ece094a`](https://github.com/aethersdr/AetherSDR/commit/34ece094a) — next | still failing ([run 35188161007](https://github.com/aethersdr/AetherSDR/actions/runs/35188161007)) |

So this is deterministic and unrelated to #5763 — it is the remaining half of the #5659 fallout.

## Bisect

Carried forward from #5768, which built and ran both targets at three commits, three consecutive runs each (not flake):

| commit | `automation_tx_watchdog_test` |
|---|---|
| `4a70e2b4` — parent of #5659 | 0 failures |
| `aea9f6dc` — #5659 | 2 failures |
| `85fdf816` — `main` at the time | 2 failures |

## The open question

#5768 deliberately did not decide this, and it is not an agent's call to make:

> The assertion texts are that change's own subject matter — watchdog cleanup after synchronous replacement ... so the likeliest reading is that the tests encode the previous ownership contract and the change moved it, rather than that the change is wrong. I have not tried to decide which; that is @rfoust's call.

#5659 is *"aetherd: Preserve desktop TX producer ownership through queued work"*. Either the test encodes a superseded ownership contract and should be updated, or the change regressed watchdog cleanup identity-recheck. Given this is TX keying-path behaviour (Principle VI), it is worth an explicit ruling rather than whichever change makes the suite green.

## Why CI does not gate on this

`.github/workflows/ci.yml` states the test gate is frozen and does not run the suite; its `ctest -R` steps name a fixed short list containing neither target. The required checks on #5659 were a compile result. `Full Suite` is the workflow that sees this, and it is not a required context.

cc @rfoust

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by ten9876** [comment]
**Correction to the framing above — this does not need a contract ruling.** PR #5789 has the fix.

I instrumented the fixture rather than reasoning from the diff, and both assertions turn out to have one cause that is not about TX ownership:

`RecordingBackend::capabilities()` does not declare `twoToneGenerator`, and #5516 gated `txtest twotone` on that record. The request is refused outright — `{"error":"two-tone generation is not implemented on this radio…","ok":false}` — so the Tune operation never starts. Assertion 1 then sees `[atu:off mox:off]` with `tune:off` missing, and assertion 2 is downstream of it: its `tuneWriter` hook fires on a `tune(false)` write that never happens, so it records nothing at all.

So this is the same #5516 × #5659 semantic merge conflict that broke `automation_persist_diagnostics_test` (fixed by #5675), not a behaviour change in #5659. #5516 added the gate at 20:52; #5659 introduced this stub without the record at 03:38 the next day; each was green on its own base.

Four lines, test-only, 2 failures → 0 over three consecutive runs, and no aetherd ratchet moves (`twoToneGenerator` is a capability record, so the frozen bool count stays at 71).

Apologies for the noise, @rfoust — the `cc` on this issue was based on #5768's reading and you can disregard it.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by ten9876** [comment]
Correcting the record before this costs @rfoust a ruling that is not needed: **the premise is wrong — these two assertions do not come from #5659.**

This issue and #5768 both rest on a measurement of 2 failures at `aea9f6dc4`. That does not reproduce. Built and run on Linux, RelWithDebInfo, `ninja automation_tx_watchdog_test`, three consecutive runs per tree:

| tree | PASS | FAIL |
|---|---|---|
| `aea9f6dc4` — #5659, pristine | **74** | **0** |
| #5772 with its fix reverted | 72 | **2** — the two named here |
| #5772 head `ece4b7c44` | **74** | **0** |

`aea9f6dc4` is clean, three for three.

The decisive part is not the count but the code: **`RadioCapabilities::TwoToneGenerator` does not exist at `aea9f6dc4` at all.** #5516 introduced the struct as well as the gate that reads it. So there is no capability refusal available at `aea9f6dc` to produce these failures, and the fix cannot even be compiled against that commit:

```
tests/automation_tx_watchdog_test.cpp:93:52: error:
  'TwoToneGenerator' is not a member of 'AetherSDR::RadioCapabilities'
```

The real cause is a one-line fixture gap introduced when #5516's gate landed: `RecordingBackend` never declared a `twoToneGenerator`, so `txtest twotone` was refused before keying, no tune started, and the watchdog cleanup the two assertions check had nothing to stop. The watchdog itself is intact — this is not TX-keying behaviour and needs no Principle VI ruling.

#5768's bisect was macOS with a local `MainWindow.h` `HAVE_HIDAPI` patch (#5767); whatever it measured at `aea9f6dc`, it does not hold up here.

Closing — fixed by #5772. `Full Suite` on `main` is the check that settles it, and I am verifying it on the squash commit after the merge fires.

cc @rfoust @on8st
